# Generated by Django 5.2 on 2025-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acto',
            fields=[
                ('id_acto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fec_inicio', models.DateTimeField()),
                ('fec_final', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
