# Generated by Django 5.2 on 2025-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acto',
            name='fec_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acto',
            name='fec_inicio',
            field=models.DateField(),
        ),
    ]
