# Generated by Django 5.2 on 2025-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_acto_fec_final_alter_acto_fec_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acto',
            name='fec_final',
        ),
        migrations.AddField(
            model_name='acto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acto',
            name='fec_inicio',
            field=models.DateTimeField(),
        ),
    ]
