# Generated by Django 5.2 on 2025-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_acto_fec_final_acto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
